name: Diagnostic - Find Tizen Studio Path

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libncurses6 zip
        
    - name: Install Tizen Studio
      run: |
        wget -q https://download.tizen.org/sdk/Installer/tizen-studio_6.1/web-cli_Tizen_Studio_6.1_ubuntu-64.bin
        chmod +x web-cli_Tizen_Studio_6.1_ubuntu-64.bin
        ./web-cli_Tizen_Studio_6.1_ubuntu-64.bin --accept-license --no-java-check -- /home/runner/tizen-studio
        
    - name: List all files to find installation path
      run: |
        ls -R /home/runner
